apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoo-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zoo-backend
  template:
    metadata:
      labels:
        app: zoo-backend
    spec:
      containers:
      - name: zoo-backend
        image: 
        envFrom:
        - configMapRef:
            name: zoo-backend-config
        ports:
        - containerPort: 3000